/*
  Sketch generated by the Arduino IoT Cloud Thing "3.2C"
  https://create.arduino.cc/cloud/things/0201f49c-ed94-4111-b07d-2f6e6fe02413

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLuminousIntensity light_val;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int led = 4;

#include <hp_BH1750.h>
#include <Wire.h>

hp_BH1750 lightMeter;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  pinMode(led, OUTPUT);

  Wire.begin();

  Serial.println("BH1750 Test begin");
}

void loop() {

  lightMeter.start();
  light_val = lightMeter.getLux();
}

void onLightValChange() {

  if (light_val < 300)
    digitalWrite(led, HIGH);

  else
    digitalWrite(led, LOW);
}
